### PR TITLE
fixes for order and restaurant schemas

### LINKED ISSUE #20: fixes for order and restaurant schemas
- fix order schema not deleting cancelled orders,
- fix restaurant schema:

1. delete _id field
2. restaurantPicture field shouldn't be required

### PR DESCRIPTION
**Pull request by belalninja**
Fixes #20

### CODE REVIEW

File: server/server/Models/order.js [hunk 1]
```diff
@@ -103,12 +103,24 @@ const orderSchema = new mongoose.Schema(
...
+    },
+  },
+);
+
+orderSchema.index(
+  { orderDate: 1 },
+  {
+    expireAfterSeconds: 3600,
+    partialFilterExpression: {
+      orderStatus: "cancelled",
```
Comment (JanaAbuHaltam) [inline server/server/Models/order.js:122]: well done, If you want you can combine `orderStatus ` into a single index using the `$in` operator

**Review by JanaAbuHaltam — CHANGES_REQUESTED** [review]

File: server/server/Models/order.js (hunk 1 above)
Comment (belalninja) [reply server/server/Models/order.js:122]: yeah i've tried that but it is not supported with our mongoDB docker version `5`, it should be version `+6`

**Review by JanaAbuHaltam — APPROVED** [review]

File: server/server/Models/order.js (hunk 1 above)
Comment (belalninja) [reply server/server/Models/order.js:122]: image
this is supported in version `7`

image
sadly it's not supported in our version, I've tried `$and`, but didn't work
